site_name: Tian's wiki
site_url: https://tianpingan.github.io/wiki/
site_author: Tianpingan
site_description: >-
  Tianpingan的wiki页面
repo_name: wiki
repo_url: https://github.com/tianpingan/wiki/

copyright: Copyright &copy; 2022-present <a href="https://github.com/tianpingan" target="_blank" rel="noopener noreferrer">Tianpingan</a>
theme:
  name: material
  language: zh

  static_templates:
    - 404.html

  include_search_page: false
  search_index_only: true

  features:
    #- navigation.instant # 点击内部链接时，不用全部刷新页面
    # - navigation.tracking # 在url中使用标题定位锚点
    # - navigation.tabs # 顶部显示导航顶层nav（也就是第一个节点）
    # - navigation.tabs.sticky # 滚动是隐藏顶部nav，需要配合navigation.tabs使用
    # - navigation.sections # nav节点缩进
    # - navigation.expand # 不折叠左侧nav节点
    # - navigation.indexes # 指定节点index pages ，跟instant不兼容
    # - toc.integrate # 右侧生产目录
    # - toc.integrate #导航集成
    # - navigation.top # 一键回顶部
    # - header.autohide
    # - search.share # 搜索分享
    # - search.suggest # 搜索建议
    # - search.highlight #搜索高亮

    - header.autohide
    # - navigation.instant
    # - navigation.expand
    # - navigation.sections
    - navigation.tracking
    - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    # - navigation.indexes
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      primary: Blue grey
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: Blue grey
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode

plugins:
  - search:
      lang: ja
  # - git-revision-date-localized
  # - minify:
      # minify_html: true