site_name: Tian's wiki
site_url: https://tianpingan.github.io/wiki/
site_author: Tianpingan
site_description: >-
  Tianpingan的wiki页面
repo_name: wiki
repo_url: https://github.com/tianpingan/wiki/

copyright: Copyright &copy; 2022-present <a href="https://github.com/tianpingan" target="_blank" rel="noopener noreferrer">Tianpingan</a>
theme:
  name: material
  language: zh

  static_templates:
    - 404.html

  include_search_page: false
  search_index_only: true

  features:
    - header.autohide
    # - navigation.instant
    # - navigation.expand
    # - navigation.sections
    - navigation.tracking
    # - navigation.tabs
    # - navigation.tabs.sticky
    - navigation.top
    # - navigation.indexes
    - search.highlight
    - search.share
    - search.suggest
    # - toc.integrate
    - content.code.annotate
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: light blue
      primary: Blue grey
      accent: deep purple
      toggle:
        icon: material/weather-sunny
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: Blue grey
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to light mode

plugins:
  - search:
      lang: ja
  # - git-revision-date-localized
  # - minify:
      # minify_html: true